Разметка и Каталог
htmlacademy-htmlcss/1772239-sedona-36 pull request #2
Opened 2023-02-09 13:22 UTC by AlekseyKamalutdinov

Не получилось отправить с первого раза, файлы про дублировались

2023-02-09 22:58 UTC, AlekseyKamalutdinov commented
2 И 3 задание  [Графика и разметка](https://github.com/htmlacademy-htmlcss/1772239-sedona-36/pull/2/commits/d0de8a2701c1ed2eaed83f2a69b87f9d36d2796c) (актуальное)

2023-02-10 20:54 UTC, mkolotovich requested changes
исправьте комментарии

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +        <ul class="navigation-list">
А где логотип потеряли?

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <a class="navigation-link" href="about.html" >Главная</a>
по заданию - Если страница существует в макете, то на неё должна вести соответствующая ссылка, например, `<a href="catalog.html">`. Страницы about нет в макете. Тут должна быть ссылка либо на index.html либо вообще заглушка.

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <a class="navigation-link" href="faq.html">Гостиницы</a>
здесь должна быть ссылка на catalog.html

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <a class="navigation-link" href="catalog.html">О Седоне</a>
а здесь по заданию - Если страницы нет в макете, то ссылка на неё должна быть следующего вида — `<a href="#"></a>`.

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +<img class="logo" src="images/Sedona.png" width="456.7px" height="212.77px" left="0px" top="139px" alt="Логотип Седоны">
по заданию - используйте для изображений подходящие форматы. Если в макете изображение в векторе то и экспортировать его нужно тоже в векторе. К тому же вы экспортировали не все изображения. По макету тут 3 изображения, а вы экспортировали только два

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +<h2 class="intro-Description" >Седона — небольшой городок в Аризоне,<br>заслуживающий большего!
уберите тег `<br>` он здесь лищний. Используйте этот тег только в тех случаях когда невозможно сделать перенос как на макете с помощью стилей. Здесь можно сделать перенос стилями.

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <h4 class="adventeges-title">Настоящий <br>городок</h4>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <p class="adventeges-desription">Седона — не аттракцион для <br>туристов, там течёт своя <br>жизнь</p>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <p class="adventeges-desription">Седона — не аттракцион для <br>туристов, там течёт своя <br>жизнь</p>
А где изображение?

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +<img class="logo" src="images/Sedona.png" width="456.7px" height="212.77px" left="0px" top="139px" alt="Логотип Седоны">
пропустили изображение декоративной рамки

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <h4 class="adventeges-title">Небольшая <br>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <p class="adventeges-desription">Все достопримечательности<br>находятся очень близко</p>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <h4 class="adventeges-title">Красивая <br>Дорога</h4>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <p class="adventeges-desription">Ехать в Седону из Лас-Вегаса<br> совсем не скучно!</p>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <h4 class="adventeges-title">Мало<br>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <p class="adventeges-desription">Большинство едет в Гранд<br>Каньон и толпится там</p>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <section>
пропустили изображение

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <h4 class="adventeges-title">Там есть <br>мост дьявола</h4>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +            <p class="adventeges-desription">Да, по нему можно пройти! <br>Если вы осмелитесь, <br>разумеется</p>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +                </p>
вот это я бы вынес в отдельный section и положил на уровень вверх

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +                <h2 class="intro-Description" >Приезжайте в Седону отдохнуть<br> в комфорте и уюте!
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +                <p class="adventeges-desription">Рекомендуем пожитьв<br>B настоящем мотеле, <br>
пожитьв - такого слова нет) Пропустили пробел. Лишняя буква - B и уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +                    топовый фирменный бургер,<br> вы не разочаруетесь!</p>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +                    но и настоящего местного <br>производства</p>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +      <button class="button" type="submit">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
type="submit" используется для отправки формы. Тут у вас формы нет поэтому используйте type="button"

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +      </section>
это не относится к подвалу. Перенесите это в тег main

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +        <p>Только полезная информация и никакого спама,<br> честное бойскаутское!</p>
уберите `<br>`

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +          </p>
зачем оборачивать input в p? Если и хотите обернуть то оборачивайте лучше в тег label

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +        </ul>
перенесите это в предыдущий section

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +          </li>
в макете этот элемент первый в списке соц. сетей

2023-02-10 20:54 UTC, mkolotovich commented on index.html
> +        <p><a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy </a></p>
это бы я вынес на уровень вверх и у нас есть критерий https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06. Я считаю, что тег р здесь избыточен. Также логотипы необходимо вставлять изображением, а не текстом

2023-02-10 21:37 UTC, mkolotovich requested changes
переименуйте файл в catalog.html и исправьте комментарии

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +            <a class="navigation-link" href="about.html" >Главная</a>
главная это у нас страница - index.html, а не about.html

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +            <a class="navigation-link navigation-link-current" href="faq.html">Гостиницы</a>
здесь должна быть ссылка на - catalog.html

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +            <a class="navigation-link" href="catalog.html">О Седоне</a>
Если страницы нет в макете, то ссылка на неё должна быть следующего вида — `<a href="#"></a>`.

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +    <a class="breadcrumbs-link">Каталог</a>
в макете тут текст - Гостиницы

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +                        </label>
эти теги у вас закрываются, но не открываются. Почему?

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +                      </label>
эти теги у вас закрываются, но не открываются. Почему?

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +                      </label>
не размечен блок Стоимость, ₽:

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +    <button class="button" type="submit">Приминить</button>
тут в макете текст - Применить

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +    <button class="button" type="submit">Сбросить</button>
тут должен быть type="reset"

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +    <option value="cheap">Сначала дешёвое</option>
в макете - Сначала дешевые и это значение по умолчанию(атрибут selected)

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +      <img class="product-card-image" src="images/hotel-1.jpg" height="212px" width="300px" left="20px"  top="20px" alt="">
что это за атрибуты left="20px"  top="20px"? По заданию - укажите размер изображений без пикселей; заполните у изображений атрибут alt.

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +      </div>
вместо всего этого должны быть изображения

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +      <img class="product-card-image" src="images/hotel-2.jpg" height="212px" width="300px" left="20px"  top="20px" alt="">
что это за атрибуты left="20px" top="20px"? По заданию - укажите размер изображений без пикселей; заполните у изображений атрибут alt.

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +    <a class="product-card-button-favorites" href="#">в избранное</a>
тут в макете текст - в избранном

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +      </div>
вместо всего этого должны быть изображения

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +      <img class="product-card-image" src="images/hotel-3.jpg" height="212px" width="300px" left="20px"  top="20px" alt="">
что это за атрибуты left="20px" top="20px"? По заданию - укажите размер изображений без пикселей; заполните у изображений атрибут alt.

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +      </div>
вместо всего этого должны быть изображения звезд

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +      <img class="product-card-image" src="images/hotel-4.jpg" height="212px" width="300px" left="20px"  top="20px" alt="">
что это за атрибуты left="20px" top="20px"? По заданию - укажите размер изображений без пикселей; заполните у изображений атрибут alt.

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +    <p class="product-card-price">От 1500 ₽</b>
тут открывается тег p и закрывается тег b

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +    </div>
вместо всего этого должны быть изображения звезд

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +  </ul>
этот список вынесите на уровень вверх

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +<section class="catalog-products">
если в блоке нет заголовка то лучше использовать div

2023-02-10 21:37 UTC, mkolotovich commented on Catalog.html
> +    </footer>
разметьте как на главной

2023-02-14 19:45 UTC, mkolotovich commented on index.html
> +<h2 class="intro-Description" >Седона — небольшой городок в Аризоне,<br>заслуживающий большего!
добавьте пробел после запятой для правильного переноса

2023-02-14 19:55 UTC, mkolotovich commented on index.html
> +                    топовый фирменный бургер,<br> вы не разочаруетесь!</p>
первый br оставьте, он нужен. А вот второй удалите

2023-02-14 19:56 UTC, mkolotovich commented on index.html
> +                    но и настоящего местного <br>производства</p>
тут тоже первый br верните обратно

2023-02-14 19:59 UTC, mkolotovich commented on index.html
> +          </p>
тега lebel не существует. У вас опечатка.

2023-02-14 20:05 UTC, mkolotovich commented on index.html
> +        </ul>
по макету у нас идут вначале соц. сети, потом телефон, потом логотип. Измените порядок элементов, чтобы был как на макете

2023-02-14 20:24 UTC, mkolotovich commented on Catalog.html
> +    </div>
в макете тут 2 звезды

2023-02-14 20:26 UTC, mkolotovich requested changes
исправьте не схлопнутые комментарии с прошлой проверки

2023-02-15 19:41 UTC, mkolotovich commented on Catalog.html
> +    <a class="breadcrumbs-link">Каталог</a>
сделайте текст гостиницы, тоже пунктом списка. Как у вас и было раньше

2023-02-15 19:48 UTC, mkolotovich requested changes
исправьте не схлопнутые комментарии с прошлой проверки

2023-02-16 19:48 UTC, mkolotovich requested changes
исправьте комментарии с прошлых проверок плюс добавились новые

2023-02-16 19:48 UTC, mkolotovich commented on Catalog.html
> +          <img class="page-header-logo" alt="Логотип Седона." src="#">
почему не указали путь, на главной же указали путь к изображению

2023-02-16 19:48 UTC, mkolotovich commented on Catalog.html
> +    <input type="range" id="price" name="price" min="0" max="9000" step="1">
тут надо сделать кастомный ползунок(с двумя ручками). Можно разметить например дивами или спанами

2023-02-16 19:48 UTC, mkolotovich commented on Catalog.html
> +        <h2 class="visually-hidden"></h2>>
Странный пустой скрытый заголовок. Уберите его

2023-02-17 16:11 UTC, AlekseyKamalutdinov commented
!

2023-02-17 19:59 UTC, mkolotovich commented on Catalog.html
> +    <input type="range" id="price" name="price" min="0" max="9000" step="1">
этот инпут удалите

2023-02-17 20:08 UTC, mkolotovich requested changes
исправьте комментарии с прошлых проверок, плюс добавились новые

2023-02-17 20:08 UTC, mkolotovich commented on index.html
> +            </div>
это лучше разметить например section'ами. Оберните это в один элемент, например див и вынесите на уровень вверх

2023-02-17 20:08 UTC, mkolotovich commented on catalog.html
> +  <div class="pagination">
это лишняя обертка. У нас есть критерий - https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06

2023-02-17 20:08 UTC, mkolotovich commented on catalog.html
> +</section>
вот это всё вынесите на уровень вверх

2023-02-17 20:08 UTC, mkolotovich commented on catalog.html
> +  <output name="price"></output>
зачем вам этот элемент? уберите его

2023-02-18 21:15 UTC, mkolotovich requested changes
исправьте комментарии по внутренней странице с прошлых проверок

2023-02-20 19:46 UTC, merged