Домашняя работа 24.02
htmlacademy-htmlcss/1772239-sedona-36 pull request #3
Opened 2023-02-24 18:16 UTC by AlekseyKamalutdinov

Базовая стилизация всех страниц, убежал немного вперед

2023-02-25 15:19 UTC, mkolotovich requested changes

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +    color: #030303; }
в макете цвет #000000;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +    padding-bottom: 25px;
задайте color: #000000;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  padding-right: 275px;
задайте font-size: 22px;
line-height: 26px;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  padding-right: 113px;
задайте color: #000000;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +    text-transform: uppercase;
задайте font-size: 30px;
line-height: 36px;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  .services-description p {
уберите из селектора - p

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +    text-transform: uppercase;
задайте color: #000000;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +        border: none;
задайте font-size: 18px;
    line-height: 24px; font-family: 'PT Sans';

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +        border-style: none;
задайте font-family: 'PT Sans';

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +
создайте селектор .field::placeholder и задайте ему   color: #000000;
  opacity: 0.6;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +    color: inherit;
задайте color: #000000;

2023-02-25 15:19 UTC, mkolotovich commented on catalog.html
> +          <img class="page-header-logo" src="images/logo.svg" width="140" height="70"
неверно указано имя файла, у вас файл называется logo!!

2023-02-25 15:19 UTC, mkolotovich commented on catalog.html
> -      <input type="number" placeholder="9000">
верните эти инпуты обратно

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  height: 36px;
задайте font-family: 'PT Sans';

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  height: 36px;
задайте font-family: 'PT Sans'; background: transparent;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  margin-top: 50px;
задайте color: #000000;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  margin-top: 50px;
задайте font-family: 'PT Sans'; font-size: 18px;
line-height: 21px; color: #333333;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  font-weight: 700;
задайте color: #000000;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +
Создайте селектор .hotel-card и задайте ему     text-transform: capitalize;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  padding: 8px 26px;
задайте color: #FFFFFF;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +  padding: 8px 20px;
задайте color: #FFFFFF;

2023-02-25 15:19 UTC, mkolotovich commented on catalog.html
> +          <p class="rating">рейтинг:5,0</p>
поставьте пробел после двоеточия

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +}
перенесите это правило после правила .pagination-link

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +
создайте селектор .page-footer-title-catalog и задайте ему font-size: 30px;
line-height: 36px; color: #000000; text-transform: uppercase;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +
создайте селектор .page-footer-title и задайте ему font-size: 22px;
line-height: 26px;

2023-02-25 15:19 UTC, mkolotovich commented on styles/styles.css
> +    min-height: 22px;
задайте font-size: 16px;
line-height: 20px; color: #FFFFFF; background: #756157; text-transform: uppercase;

2023-02-25 15:19 UTC, mkolotovich commented on catalog.html
> +            <a class="hotel-card-button button-green" href="#">в избранное</a>
тут в макете текст - в избранном

2023-02-25 19:33 UTC, AlekseyKamalutdinov commented on styles/styles.css
> +  .services-description p {
Написал в тг

2023-02-26 09:26 UTC, mkolotovich commented on styles/styles.css
> +  padding-right: 113px;
создайте селектор .advantages-item:nth-child(n +2):nth-child(-n+ 4) .advantages-title и color: #000000; задайте в нем, а из селектора .advantages-title уберите color: #000000;

2023-02-26 09:29 UTC, mkolotovich commented on styles/styles.css
> +    text-transform: uppercase;
измените селектор на .services-about .services-title

2023-02-26 09:38 UTC, mkolotovich commented on catalog.html
> -      <input type="number" placeholder="9000">
создайте селектор .catalog-filter > input и задайте ему font-family: 'PT Sans';
font-weight: 700;
font-size: 18px;
line-height: 24px;. Создайте селектор .catalog-filter > input::placeholder и задайте ему color: #000000;

2023-02-26 09:40 UTC, mkolotovich commented on styles/styles.css
> +  height: 36px;
вот это свойство     background-color: rgb(107, 134, 157); уберите из правила

2023-02-26 09:45 UTC, mkolotovich commented on styles/styles.css
> +  font-weight: 700;
создайте селектор .hotel-card-link и задайте ему text-decoration: none;

2023-02-26 09:55 UTC, mkolotovich requested changes
исправьте не схлопнутые комментарии с прошлой проверки плюс добавились новые

2023-02-26 09:55 UTC, mkolotovich commented on styles/styles.css
> +    color: inherit;
задайте color: #FFFFFF;

2023-02-26 09:55 UTC, mkolotovich commented on styles/styles.css
>      color: #030202;
в макете color: #FFFFFF;

2023-02-27 19:49 UTC, mkolotovich commented on catalog.html
> +            <a class="hotel-card-button button-green" href="#">в избранное</a>
этот текст только у второй карточки, у остальных текст - в избранное. Селектору .button-green задайте color: #FFFFFF;

2023-02-27 19:52 UTC, mkolotovich requested changes
исправьте 2 комментария с прошлых проверок

2023-02-27 20:37 UTC, merged